Repository docker-mailserver/docker-mailserver, pull requests merged in 2019-08, with the labels that each got.

#1185 Add PERMIT_DOCKER=connected-networks
  Makefile
  README.md
  target/start-mailserver.sh
  test/tests.bats
Labels: build broken

#1218 Fixed opendkim config on multiple nameservers
  target/start-mailserver.sh
Labels: bug

#1245 Use Dovecot repo to fix cve-2019-11500 take two
  Dockerfile
Labels: postfix / dovecot related, security
