Repository docker-mailserver/docker-mailserver, pull requests merged in 2020-12, with the labels that each got.

#1708 Add more config options to saslauthd.conf
  README.md
  mailserver.env
  target/start-mailserver.sh
Labels: can be merged, feature request, ldap related, priority 3 [LOW]

#1703 Small fixes for extracting certs from the acme.json file
  target/helper-functions.sh
  target/start-mailserver.sh
  test/config/letsencrypt/acme.json
Labels: bug, priority 2 [MEDIUM], script related, ssl/tls

#1711 Get rid of syslogd warnings about kernel logging.
  Dockerfile
  README.md
Labels: enhancement, priority 3 [LOW]

#1705 Add purge cron job for Dovecot dbox format
  Dockerfile
  target/dovecot/dovecot-purge.cron
  target/start-mailserver.sh
Labels: enhancement, feature request, postfix / dovecot related, priority 3 [LOW]
