Repository docker-mailserver/docker-mailserver, pull requests merged in 2020-04, with the labels that each got.

#1435 amavis: fix config permission
  target/start-mailserver.sh
Labels: security

#1424 fail2ban: ignore connections with auth attempt
  Dockerfile
  target/fail2ban/filter.d/dovecot.conf
Labels: firewall, security

#1451 Fix error #792 in logrotate
  Dockerfile
Labels: bug

#1450 Upgrade packages
  Dockerfile
Labels: enhancement

#1458 Cleanup obsolete file removal
  Dockerfile
Labels: enhancement

#1469 Feature: quota per mailbox
  Dockerfile
  Makefile
  config/dovecot-quotas.cf
  setup.sh
  target/bin/delmailuser
  target/bin/delquota
  target/bin/setquota
  target/check-for-changes.sh
  target/dovecot/10-mail.conf
  target/dovecot/20-imap.conf
  target/dovecot/90-quota.conf
  target/dovecot/scripts/quota-warning.sh
  target/start-mailserver.sh
  test/mail_smtponly.bats
  test/mail_with_ldap.bats
  test/test-files/email-templates/quota-exceeded.txt
  test/tests.bats
Labels: enhancement

#1463 Fix issue #1461- use a recommended dh group instead of a self-generated one
  Dockerfile
  Makefile
  target/dovecot/10-ssl.conf
  target/shared/ffdhe4096.pem
  target/shared/ffdhe4096.pem.sha512sum
  target/start-mailserver.sh
  test/config/dhparams.pem
  test/config/dovecot-lmtp/dh.pem
  test/config/relay-hosts/dhparams.pem
  test/mail_dhparams_default.bats
  test/mail_dhparams_manual_not_one_dir.bats
  test/mail_dhparams_manual_one_dir.bats
  test/test-files/ssl/custom-dhe-params.pem
  test/tests.bats
Labels: security

#1474 chore: Remove obsolete postfix parameter `smtpd_use_tls`
  target/postfix/main.cf
Labels: security, ssl/tls
