Repository docker-mailserver/docker-mailserver, pull requests merged in 2020-09, with the labels that each got.

#1596 Populate relayhost_map from virtual accounts (and other fixes)
  target/check-for-changes.sh
  target/helper_functions.sh
  target/start-mailserver.sh
  test/config/relay-hosts/postfix-virtual.cf
  test/mail_ssl_letsencrypt.bats
  test/mail_with_relays.bats
  test/tests.bats
Labels: enhancement

#1601 Changes from #1599 without `start-mailserver.sh`
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  setup.sh
  target/check-for-changes.sh
  target/fail2ban-wrapper.sh
  target/helper_functions.sh
  target/postfix-wrapper.sh
  target/postsrsd-wrapper.sh
  target/start-mailserver.sh
  target/supervisor/conf.d/supervisor-app.conf
Labels: can be merged, documentation, enhancement

#1604 Fix for #1603
  setup.sh
Labels: bug

#1614 Getting rid of ELK & Update Compose
  README.md
  config/filebeat.docker.yml
  docker-compose.elk.yml.dist
  docker-compose.filebeat.yml.dist
  docker-compose.yml.dist
  elk/.env.dist
  elk/02-beats-input.conf
  elk/10-syslog.conf
  elk/16-amavis.conf
  elk/Dockerfile
  elk/amavis.grok
  elk/docker-compose.yml.dist
  setup.sh
Labels: can be merged, priority 2 [MEDIUM], roadmap

#1605 Complete refactoring for `start-mailserver.sh`
  CONTRIBUTING.md
  Makefile
  target/dovecot/scripts/quota-warning.sh
  target/start-mailserver.sh
Labels: can be merged, enhancement, priority 2 [MEDIUM]

#1616 Remove unnecessary use of cat
  target/fail2ban-wrapper.sh
  target/postfix-wrapper.sh
  target/start-mailserver.sh
Labels: can be merged, enhancement

#1619 Formatting files according to standard
  .editorconfig
  .gitignore
  .hadolint.yaml
  .travis.yml
  Dockerfile
  Makefile
  README.md
  target/bin/addmailuser
  target/dovecot/10-auth.conf
  target/dovecot/10-logging.conf
  target/dovecot/10-mail.conf
  target/dovecot/10-master.conf
  target/postfix/master.cf
  target/postsrsd/postsrsd
  target/start-mailserver.sh
  test/config/dovecot-lmtp/conf.d/10-director.conf
  test/config/dovecot-lmtp/conf.d/10-logging.conf
  test/config/dovecot-lmtp/conf.d/10-mail.conf
  test/config/dovecot-lmtp/conf.d/10-master.conf
  test/config/dovecot-lmtp/conf.d/20-imap.conf
  test/config/dovecot-lmtp/conf.d/20-pop3.conf
  test/config/dovecot-lmtp/conf.d/auth-ldap.conf.ext
  test/config/dovecot-lmtp/conf.d/auth-system.conf.ext
  test/config/dovecot-lmtp/dovecot-sql.conf.ext
  test/config/dovecot-lmtp/dovecot.conf
  test/config/letsencrypt/mail.my-domain.com/cert.pem
  test/config/letsencrypt/mail.my-domain.com/chain.pem
  test/config/letsencrypt/mail.my-domain.com/fullchain.pem
  test/config/letsencrypt/mail.my-domain.com/privkey.pem
  test/config/letsencrypt/my-domain.com/cert.pem
  test/config/letsencrypt/my-domain.com/chain.pem
  test/config/letsencrypt/my-domain.com/fullchain.pem
  test/config/letsencrypt/my-domain.com/key.pem
  test/config/opendkim/TrustedHosts
  test/config/user-patches/user-patches.sh
  test/docker-openldap/bootstrap/ldif/02_user-email.ldif
  test/docker-openldap/bootstrap/schema/mmc/postfix-book.schema
Labels: enhancement, priority 3 [LOW]

#1621 added option to use non-default network-interface, resolves #1227
  CODE_OF_CONDUCT.md
  README.md
  env-mailserver.dist
  setup.sh
  target/helper_functions.sh
  target/start-mailserver.sh
Labels: enhancement, feature request, priority 2 [MEDIUM]

#1627 Dovecot community repo info removed
  Dockerfile
Labels: enhancement

#1628 possible fix for tomav#1383
  config/user-patches.sh.dist
  target/start-mailserver.sh
Labels: enhancement, priority 3 [LOW]
