Repository docker-mailserver/docker-mailserver, pull requests merged in 2020-10, with the labels that each got.

#1634 fix: use self-signed cert for dovecot
  target/start-mailserver.sh
Labels: bug, can be merged, priority 2 [MEDIUM]

#1635 streamlined all scripts adhering to CONTRIBUTING.md
  CONTRIBUTING.md
  target/check-for-changes.sh
  target/helper_functions.sh
  target/postsrsd-wrapper.sh
  target/start-mailserver.sh
Labels: enhancement, priority 3 [LOW], script related

#1638 Comments updated
  config/user-patches.sh.dist
Labels: can be merged, documentation, enhancement, priority 3 [LOW]

#1636 Outsourced linting tests into its own file
  .travis.yml
  Makefile
  setup.sh
  test/linting/.hadolint.yaml
  test/linting/lint.sh
  test/tests.bats
Labels: can be merged, enhancement, priority 2 [MEDIUM], script related, test related

#1641 Miscellaneous cleanup / housekeeping
  .env.dist
  .gitignore
  .travis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  setup.sh
  target/check-for-changes.sh
  target/helper_functions.sh
  target/start-mailserver.sh
Labels: can be merged, documentation, enhancement, priority 3 [LOW], script related

#1632 Remove write access to group and others to Amavis configuration files
  Dockerfile
Labels: enhancement, priority 3 [LOW]

#1658 Quotes removed to have a uniform style
  target/start-mailserver.sh
Labels: enhancement, priority 3 [LOW], script related

#1660 Exchanging `.dist` files
  .editorconfig
  .gitignore
  README.md
  docker-compose.yml
  env-mailserver
  template.env
Labels: can be merged, enhancement, priority 3 [LOW]

#1653 Documentation and Script Updates trying to fix #1647
  README.md
  target/start-mailserver.sh
Labels: can be merged, enhancement, postfix / dovecot related, priority 1 [HIGH], script related

#1654 Complete Refactor for `target/bin`
  CONTRIBUTING.md
  Dockerfile
  Makefile
  hooks/build
  setup.sh
  target/bin-helper.sh
  target/bin/addalias
  target/bin/addmailuser
  target/bin/addrelayhost
  target/bin/addsaslpassword
  target/bin/debug-fetchmail
  target/bin/delalias
  target/bin/delmailuser
  target/bin/delquota
  target/bin/excluderelaydomain
  target/bin/fail2ban
  target/bin/generate-dkim-config
  target/bin/generate-dkim-domain
  target/bin/generate-ssl-certificate
  target/bin/listalias
  target/bin/listmailuser
  target/bin/postfix-summary
  target/bin/report-pflogsumm-yesterday
  target/bin/restrict-access
  target/bin/setquota
  target/bin/setup-fetchmail
  target/bin/updatemailuser
  target/bin/virus-wiper
  target/check-for-changes.sh
  target/fail2ban-wrapper.sh
  target/helper-functions.sh
  target/postfix-wrapper.sh
  target/postsrsd-wrapper.sh
  target/start-mailserver.sh
  test/helper_functions.bats
  test/linting/lint.sh
  test/mail_fail2ban.bats
Labels: can be merged, enhancement, help wanted, priority 1 [HIGH], script related, test related

#1657 silence errorneous output when not generating reports
  target/start-mailserver.sh
Labels: build broken, can be merged, enhancement, help wanted, priority 3 [LOW], script related

#1613 Extract even more tests
  .github/CONTRIBUTING.md
  .gitignore
  .travis.yml
  Makefile
  target/check-for-changes.sh
  test/config/duplicate_config_test/marker
  test/config/without-accounts/.gitkeep
  test/default_relay_host.bats
  test/mail_dhparams_default.bats
  test/mail_dhparams_manual_not_one_dir.bats
  test/mail_dhparams_manual_one_dir.bats
  test/mail_disabled_clamav_spamassassin.bats
  test/mail_fail2ban.bats
  test/mail_fetchmail.bats
  test/mail_lmtp_ip.bats
  test/mail_override_hostname.bats
  test/mail_pop3.bats
  test/mail_postfix_inet.bats
  test/mail_postscreen.bats
  test/mail_privacy.bats
  test/mail_quotas_disabled.bats
  test/mail_smtponly.bats
  test/mail_spam_bounced.bats
  test/mail_spam_junk_folder.bats
  test/mail_special_use_folders.bats
  test/mail_srs_domainname.bats
  test/mail_ssl_letsencrypt.bats
  test/mail_ssl_manual.bats
  test/mail_undef_spam_subject.bats
  test/mail_with_imap.bats
  test/mail_with_ldap.bats
  test/mail_with_mdbox.bats
  test/mail_with_postgrey.bats
  test/mail_with_postgrey_disabled_by_default.bats
  test/mail_with_relays.bats
  test/mail_with_sdbox.bats
  test/permit_docker.bats
  test/test_helper.bats
  test/test_helper/common.bash
  test/tests.bats
Labels: build broken, can be merged, enhancement, priority 1 [HIGH], test related

#1662 Env Update 2
  .dockerignore
  README.md
  compose.env
  docker-compose.yml
  mailserver.env
  template.env
Labels: can be merged, documentation, enhancement, priority 3 [LOW]
