Repository docker-mailserver/docker-mailserver, pull requests merged in 2020-11, with the labels that each got.

#1672 Add SELinux support
  README.md
  compose.env
  docker-compose.yml
  setup.sh
Labels: feature request, priority 3 [LOW]

#1679 F2B script unusable - fixes #1677
  target/bin/fail2ban
  test/mail_fail2ban.bats
Labels: bug, priority 2 [MEDIUM], script related, test related

#1680 Shellcheck for test/*.bats
  CONTRIBUTING.md
  test/default_relay_host.bats
  test/helper_functions.bats
  test/linting/lint.sh
  test/mail_dhparams_default.bats
  test/mail_dhparams_manual_not_one_dir.bats
  test/mail_dhparams_manual_one_dir.bats
  test/mail_disabled_clamav_spamassassin.bats
  test/mail_fail2ban.bats
  test/mail_fetchmail.bats
  test/mail_lmtp_ip.bats
  test/mail_override_hostname.bats
  test/mail_pop3.bats
  test/mail_postscreen.bats
  test/mail_privacy.bats
  test/mail_smtponly.bats
  test/mail_special_use_folders.bats
  test/mail_srs_domainname.bats
  test/mail_ssl_letsencrypt.bats
  test/mail_ssl_manual.bats
  test/mail_undef_spam_subject.bats
  test/mail_with_imap.bats
  test/mail_with_ldap.bats
  test/mail_with_mdbox.bats
  test/mail_with_postgrey.bats
  test/mail_with_postgrey_disabled_by_default.bats
  test/mail_with_relays.bats
  test/mail_with_sdbox.bats
  test/permit_docker.bats
  test/test_helper.bats
  test/tests.bats
Labels: enhancement, priority 2 [MEDIUM], script related, test related

#1667 Change default logrotate settings for /var/mail/maillog
  target/start-mailserver.sh
Labels: enhancement, priority 2 [MEDIUM]

#1682 Housekeeping
  .dockerignore
  CONTRIBUTING.md
  Makefile
  README.md
  compose.env
  docker-compose.yml
  hooks/build
  mailserver.env
  setup.sh
  target/bin-helper.sh
  target/check-for-changes.sh
  target/dovecot/scripts/quota-warning.sh
  target/fail2ban-wrapper.sh
  target/helper-functions.sh
  target/postfix-wrapper.sh
  target/postgrey/postgrey.init
  target/postsrsd-wrapper.sh
  target/start-mailserver.sh
  test/linting/lint.sh
  test/mail_smtponly.bats
Labels: enhancement, priority 2 [MEDIUM], script related, test related

#1683 Create docs for missing DOVECOT vars in README.md
  README.md
Labels: can be merged, documentation, enhancement, postfix / dovecot related, priority 2 [MEDIUM]

#1686 Correting Makefle - Fixing #1685
  Makefile
Labels: bug, priority 1 [HIGH]

#1690 Add additional pem file for _monitored_files_checksums
  target/helper-functions.sh
Labels: can be merged, enhancement, priority 3 [LOW]
