Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-01, with the labels that each got.

#1737 Fix shebangs
  config/user-patches.sh.dist
  target/start-mailserver.sh
  test/config/sieve-pipe/pipe_to_tmp
  test/config/user-patches/user-patches.sh
Labels: enhancement, priority 3 [LOW], script related

#1754 FIX: Postfix configuration in `start-mailserver.sh` for regex
  target/scripts/start-mailserver.sh
Labels: area/scripts, kind/bug, priority/medium, service/postfix

#1756 FIX: build inconsistencies for razor
  Dockerfile
Labels: area/ci, area/enhancement, kind/bug, priority/high

#1758 Improve logging significantly – color is back!
  ENVIRONMENT.md
  target/scripts/helper-functions.sh
  target/scripts/start-mailserver.sh
  target/supervisor/conf.d/supervisor-app.conf
  target/supervisor/supervisord.conf
  test/mail_ssl_letsencrypt.bats
Labels: area/enhancement, area/scripts, kind/question, priority/high

#1763 Change tag convention and allow multiple registries
  .github/workflows/default_on_push.yml
  CONTRIBUTING.md
  README.md
Labels: area/ci, area/enhancement, kind/feature (request), pr/need review, priority/medium

#1770 Fix for issue #1769
  target/scripts/start-mailserver.sh
Labels: area/error, area/scripts, kind/bug, priority/medium

#1771 Add missing variables
  target/scripts/start-mailserver.sh
Labels: area/enhancement, area/scripts

#1753 Allow manual domains for dkim generator
  README.md
  setup.sh
  target/bin/generate-dkim-config
  target/bin/generate-dkim-domain
  test/tests.bats
Labels: area/enhancement, kind/feature (request), priority/medium, service/ldap

#1776 Replace $_ in error trap
  CONTRIBUTING.md
  setup.sh
  test/linting/lint.sh
Labels: area/enhancement, area/scripts

#1782 removing bl.spamcop.net for 8.0.1
  target/postfix/main.cf
  target/scripts/start-mailserver.sh
  test/mail_with_postgrey.bats
Labels: area/sapam, kind/bug, pr/need review, priority/high

#1783 doc: fix service name now mailserver
  README.md
Labels: area/enhancement, priority/low
