Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-09, with the labels that each got.

#2165 docs(deps): bump mkdocs-material to 7.2.6
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/dependency, kind/improvement, area/documentation

#2158 sed wrapper
  Dockerfile
  target/bin/sedfile
Labels: priority/low, area/scripts, kind/improvement

#2170 Update F2B wrapper to show possible errors with IPTables
  target/bin/fail2ban
Labels: pr/needs review, area/scripts, service/fail2ban, kind/improvement

#2134 setup.sh: docker_container first, then fall back to docker_image
  .github/workflows/test_merge_requests.yml
  setup.sh
  target/scripts/postfix-wrapper.sh
  test/mail_with_ldap.bats
  test/no_container.bats
  test/test_helper/common.bash
  test/tests.bats
Labels: area/ci, area/scripts, area/tests, kind/improvement

#2172 Update delmailuser to allow mailboxes without TLD
  target/bin/delmailuser
Labels: area/scripts, kind/improvement

#2160 Introduce issue forms and update debug output for forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  target/bin/print-environment
  target/scripts/start-mailserver.sh
Labels: area/issue, pr/needs review, kind/new feature, priority/low

#2180 Follow up on PR for fixing tests (mostly styling)
  test/test_helper.bats
  test/tests.bats
Labels: priority/low, area/tests, kind/improvement

#2175 HOSTNAME and DOMAINNAME setting improvements
  Makefile
  docs/content/config/environment.md
  target/scripts/check-for-changes.sh
  target/scripts/helper-functions.sh
  target/scripts/postsrsd-wrapper.sh
  target/scripts/start-mailserver.sh
  target/scripts/startup/check-stack.sh
  test/mail_hostname.bats
  test/mail_override_hostname.bats
  test/mail_srs_domainname.bats
Labels: priority/low, area/scripts, kind/improvement

#2174 Move setup process via script into container
  README.md
  docs/content/config/setup.sh.md
  docs/mkdocs.yml
  setup.sh
  target/bin/setup
  test/tests.bats
Labels: pr/needs review, priority/medium, area/scripts, kind/improvement

#2188 Switch to old setup.sh until release
  setup.sh
  setup.sh.10.2.0
Labels: priority/high, area/scripts, kind/improvement

#2183 Lock file create and remove improvements
  Dockerfile
  Makefile
  target/bin/addmailuser
  target/bin/delmailuser
  target/bin/setquota
  target/bin/updatemailuser
  target/scripts/check-for-changes.sh
  target/scripts/helper-functions.sh
  test/helper-functions.bats
  test/helper_functions.bats
  test/mail_changedetector.bats
Labels: pr/needs review, priority/high, area/scripts, kind/improvement

#2181 Fix delmailuser error handling
  target/bin/delmailuser
Labels: area/scripts, kind/improvement

#2192 fix: Enable DH parameters (ffdhe4096) by default
  Dockerfile
  docs/content/config/security/ssl.md
  target/scripts/startup/setup-stack.sh
  test/mail_dhparams_default.bats
  test/mail_dhparams_manual_not_one_dir.bats
  test/mail_dhparams_manual_one_dir.bats
  test/mail_tls_dhparams.bats
Labels: priority/high, area/security, kind/possible bug

#2196 fix: Remove `mkcert.sh` usage + `_setup_ssl` refactor.
  Dockerfile
  target/dovecot/10-ssl.conf
  target/scripts/helper-functions.sh
  target/scripts/startup/check-stack.sh
  target/scripts/startup/setup-stack.sh
  test/config/dovecot-lmtp/conf.d/10-ssl.conf
  test/config/dovecot-lmtp/ssl/dovecot.key
  test/config/dovecot-lmtp/ssl/dovecot.pem
  test/mail_privacy.bats
  test/mail_ssl_manual.bats
  test/mail_with_ldap.bats
  test/tests.bats
Labels: priority/medium, area/scripts, kind/improvement, pr/waiting for other pr to get merged

#2197 fix: Don't needlessly invalidate cache layers
  Dockerfile
Labels: area/ci, priority/medium, kind/improvement, pr/waiting for other pr to get merged

#2189 scripts: merge new setup.sh version for 10.2.0 again
  README.md
  docs/content/config/setup.sh.md
  setup.sh
  setup.sh.10.2.0
  target/bin/setup
  target/scripts/helper-functions.sh
Labels: kind/new feature, priority/high, area/scripts, kind/improvement

#2179 feat: rootless Podman with documentation
  docs/content/config/advanced/podman.md
  docs/mkdocs.yml
Labels: priority/low, kind/improvement, area/documentation, orchestrator/podman, pr/waiting for other pr to get merged

#2159 Update all docker-compose files to use the same version and examples
  docker-compose.yml
  docs/content/config/advanced/auth-ldap.md
  docs/content/config/advanced/full-text-search.md
  docs/content/config/advanced/kubernetes.md
  docs/content/config/advanced/override-defaults/dovecot.md
  docs/content/config/security/ssl.md
  docs/content/config/setup.sh.md
  docs/content/examples/tutorials/basic-installation.md
  docs/content/examples/tutorials/mailserver-behind-proxy.md
  docs/content/faq.md
Labels: priority/low, kind/improvement, area/documentation

#2198 tests: Refactored bounced spam test + Introduce common container setup template
  target/scripts/startup/setup-stack.sh
  test/mail_spam_bounced.bats
  test/test_helper/common.bash
Labels: priority/low, area/tests, kind/improvement

#2202 docs(deps): bump mkdocs-material to 7.2.7
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, priority/low, area/documentation

#2204 docs(deps): bump mkdocs-material to 7.2.8
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, area/documentation

#2201 make setup.sh completely non-interactive
  setup.sh
  test/linting/.ecrc.json
Labels: priority/low, area/scripts, kind/improvement

#2206 docs(chore): Normalize for consistency
  README.md
  docker-compose.yml
  docs/content/config/advanced/auth-ldap.md
  docs/content/config/advanced/full-text-search.md
  docs/content/config/advanced/kubernetes.md
  docs/content/config/advanced/mail-fetchmail.md
  docs/content/config/advanced/mail-forwarding/relay-hosts.md
  docs/content/config/advanced/mail-sieve.md
  docs/content/config/advanced/optional-config.md
  docs/content/config/advanced/override-defaults/dovecot.md
  docs/content/config/advanced/override-defaults/postfix.md
  docs/content/config/advanced/override-defaults/user-patches.md
  docs/content/config/advanced/podman.md
  docs/content/config/best-practices/autodiscover.md
  docs/content/config/best-practices/dkim.md
  docs/content/config/best-practices/dmarc.md
  docs/content/config/best-practices/spf.md
  docs/content/config/environment.md
  docs/content/config/security/fail2ban.md
  docs/content/config/security/ssl.md
  docs/content/config/security/understanding-the-ports.md
  docs/content/config/setup.sh.md
  docs/content/config/troubleshooting/debugging.md
  docs/content/config/user-management/accounts.md
  docs/content/config/user-management/aliases.md
  docs/content/contributing/coding-style.md
  docs/content/contributing/documentation.md
  docs/content/contributing/issues-and-pull-requests.md
  docs/content/examples/tutorials/basic-installation.md
  docs/content/examples/tutorials/blog-posts.md
  docs/content/examples/tutorials/mailserver-behind-proxy.md
  docs/content/examples/uses-cases/forward-only-mailserver-with-ldap-authentication.md
  docs/content/examples/uses-cases/imap-folders.md
  docs/content/faq.md
  docs/content/index.md
  docs/content/introduction.md
  docs/mkdocs.yml
  setup.sh
  target/bin/setup
  target/scripts/startup/setup-stack.sh
Labels: priority/medium, kind/improvement, area/documentation

#2207 docs(deps): bump mkdocs-material to 7.3.0
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, area/documentation

#2199 function _defunc removed
  target/scripts/helper-functions.sh
  target/scripts/start-mailserver.sh
  target/scripts/startup/check-stack.sh
  target/scripts/startup/daemons-stack.sh
  target/scripts/startup/fixes-stack.sh
  target/scripts/startup/misc-stack.sh
  target/scripts/startup/setup-stack.sh
Labels: area/scripts, kind/improvement

#2212 Update contributor workflow
  .github/workflows/contributors.yml
Labels: area/ci, kind/improvement

#2214 Update contributor workflow
  .github/workflows/contributors.yml
Labels: area/ci, kind/improvement

#2216 Update "error tracing" doc
  docs/content/contributing/coding-style.md
Labels: kind/improvement, area/documentation

#2215 Small setup.sh improvements
  setup.sh
Labels: area/scripts, kind/improvement

#2209 docs: `ssl.md` - Revise letsencrypt section
  docs/content/config/security/ssl.md
Labels: priority/low, kind/improvement, area/documentation

#2210 docs: Revise `basic-install.md`
  docs/content/examples/tutorials/basic-installation.md
Labels: priority/low, kind/improvement, area/documentation

#2164 document pre-docker build command
  docs/content/examples/tutorials/docker-build.md
  docs/mkdocs.yml
Labels: kind/improvement, area/documentation

#2222 Streamline workflow step seperation
  .github/workflows/contributors.yml
  .github/workflows/default_on_push.yml
  .github/workflows/linting.yml
  .github/workflows/scheduled_builds.yml
  .github/workflows/test_merge_requests.yml
Labels: area/ci, kind/improvement

#2226 Fix contributor workflow
  .github/workflows/contributors.yml
Labels: area/ci, kind/improvement

#2229 Run contributors workflow monthly
  .github/workflows/contributors.yml
Labels: area/ci
