Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-06, with the labels that each got.

#2021 docs: SSL - Revise self-signed cert provisioning
  docs/content/config/security/ssl.md
Labels: area/documentation

#1978 v10.0.0 release
  CHANGELOG.md
  README.md
  VERSION
  docs/content/config/advanced/optional-config.md
  docs/content/config/setup.sh.md
  setup.sh
  target/bin/generate-ssl-certificate
Labels: kind/improvement, kind/new feature, meta/help wanted, priority/high

#2000 chore(ci): Linting Improved
  .github/workflows/linting.yml
  Makefile
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
  test/linting/.ecrc.json
  test/linting/.hadolint.yaml
  test/linting/lint.sh
Labels: area/ci, area/scripts, kind/improvement, pr/needs review, priority/low

#2001 MacOS linting & testing support + docs
  .github/workflows/linting.yml
  .gitignore
  Makefile
  docs/content/contributing/issues-and-pull-requests.md
  docs/content/contributing/tests.md
  setup.sh
  target/scripts/helper-functions.sh
  test/linting/.ecrc.json
  test/linting/.hadolint.yaml
  test/linting/lint.sh
  test/mail_with_relays.bats
Labels: area/ci, area/scripts, kind/improvement, kind/new feature, os/macOS, priority/medium

#2024 chore(cleanup): Cleaned up >/dev/null in Dockerfile and fixed em dash "problem"
  .editorconfig
  CONTRIBUTING.md
  Dockerfile
  Makefile
  docs/content/contributing/coding-style.md
  mailserver.env
  setup.sh
  target/scripts/check-for-changes.sh
  target/scripts/helper-functions.sh
  target/scripts/start-mailserver.sh
  test/linting/lint.sh
  test/open_dkim.bats
  test/tests.bats
Labels: area/ci, kind/improvement, pr/needs review, priority/low

#1980 chore(scripts): Removing flock so NFS works
  Makefile
  target/bin/addmailuser
  target/bin/delmailuser
  target/bin/setquota
  target/bin/updatemailuser
  target/scripts/check-for-changes.sh
  target/scripts/helper-functions.sh
  test/linting/lint.sh
Labels: area/scripts, kind/improvement, pr/needs review, priority/low

#2035 Use bind mounts in sample config
  docker-compose.yml
  docs/content/faq.md
Labels: area/documentation, kind/improvement, meta/wip, pr/needs review, priority/low

#2041 Update postgrey whitelist
  Dockerfile
Labels: kind/improvement, priority/low, service/postgrey

#2043 reworked mail_crypt guide to make things way more simple and prepare …
  docs/content/config/security/mail_crypt.md
Labels: area/documentation, kind/improvement, priority/low, service/dovecot

#2044 Fix deletion of supervisord.pid
  target/scripts/startup/fixes-stack.sh
Labels: area/scripts, kind/improvement

#2046 Check if CONTAINER_IP could be determined
  target/scripts/helper-functions.sh
  target/scripts/startup/check-stack.sh
  target/scripts/startup/setup-stack.sh
Labels: area/scripts, kind/improvement

#2047 Follow-up #2035
  README.md
  docs/content/config/advanced/auth-ldap.md
Labels: area/documentation, kind/improvement

#2051 Use keyserver that still returns keys with user IDs
  Dockerfile
Labels: area/dependency, kind/improvement, pr/needs review, priority/medium, service/fail2ban

#2045 Adding instructions and discussion for folders
  README.md
  docs/content/examples/uses-cases/imap-folders.md
  docs/mkdocs.yml
  target/dovecot/15-mailboxes.conf
Labels: area/documentation, kind/improvement, priority/low

#2056 docs(deps): bump mkdocs-material to 7.1.9
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, area/dependency, area/documentation, kind/improvement, pr/needs review, priority/low

#2059 Install dbconfig-no-thanks package
  Dockerfile
Labels: area/dependency, kind/improvement, pr/needs review, priority/medium
