Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-08, with the labels that each got.

#2109 v10.1.0 release
  CHANGELOG.md
  README.md
  VERSION
Labels: priority/high

#2112 Add logwatch maillog.conf file to support /var/log/mail/
  Dockerfile
  target/logwatch/maillog.conf
Labels: priority/low, area/features, kind/improvement

#2118 docs(deps): bump mkdocs-material to 7.2.3
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/dependency, pr/needs review, priority/low, kind/improvement, area/documentation

#2125 docs(deps): bump mkdocs-material to 7.2.4
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/dependency, area/documentation

#2111 chore(docs): adjust K8s documentation
  docs/content/config/advanced/kubernetes.md
Labels: priority/low, meta/wip, kind/improvement, area/documentation, orchestrator/kubernetes, os/linux

#2137 reverted stopwaitsecs for postfix
  target/supervisor/conf.d/supervisor-app.conf
Labels: kind/bug, pr/needs review

#2138 docs: Add a new blog post
  docs/content/examples/tutorials/blog-posts.md
Labels: priority/low, kind/improvement, area/documentation

#2151 v10.1.1 release
  CHANGELOG.md
  README.md
  VERSION
Labels: area/dependency, pr/needs review, priority/low, kind/release

#2156 v10.1.2 release
  CHANGELOG.md
  README.md
  VERSION
Labels: priority/medium, kind/release

#2153 fix: broken documentation workflow
  .github/workflows/scripts/docs/update-versions-json.sh
Labels: area/ci, area/dependency, priority/medium, area/scripts, meta/wip, area/documentation

#2148 Change default value of ONE_DIR
  Dockerfile
  mailserver.env
  target/scripts/start-mailserver.sh
Labels: priority/low, area/scripts, kind/improvement
