Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-10, with the labels that each got.

#2235 Disable name resolution in iptables check
  target/bin/fail2ban
Labels: area/scripts, kind/improvement

#2236 Make it compatible with docker compose 2.x
  mailserver.env
Labels: priority/low, area/features, kind/improvement, orchestrator/compose

#2233 Relaxed error handling
  target/scripts/startup/fixes-stack.sh
Labels: area/scripts, kind/improvement

#2234 Update README to reflect changes of `v10.2.0`
  README.md
Labels: priority/medium, kind/improvement, area/documentation

#2265 docs(deps): bump mkdocs-material to 7.3.5
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, area/documentation

#2252 fail2ban.md: add info about running in rootless containers
  docs/content/config/security/fail2ban.md
Labels: kind/improvement, area/documentation

#2273 fix: `ONE_DIR=1` should keep correct permissions for `spool-postfix`
  target/scripts/startup/misc-stack.sh
Labels: priority/medium, kind/improvement
