Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-04, with the labels that each got.

#1878 Better incorporate the new, great documentation
  README.md
  docs/content/config/advanced/override-defaults/user-patches.md
  docs/content/index.md
  docs/mkdocs.yml
Labels: area/documentation, kind/improvement, pr/needs review, priority/medium

#1883 ci(dependency): update docker-meta action to 2.2.0
  .github/workflows/default_on_push.yml
  .github/workflows/scheduled_builds.yml
Labels: area/ci, area/dependency, pr/needs review, priority/medium

#1886 setup.sh improved
  setup.sh
Labels: area/enhancement, area/scripts, kind/improvement

#1889 docs: minor adjustments
  .github/workflows/deploy-docs.yml
  .github/workflows/pr-docs.yml
  docs/mkdocs.yml
Labels: area/ci, area/documentation, kind/improvement, kind/new feature, pr/needs review, priority/medium

#1894 ci(docs): update mkdocs-material image to version 7.1.1
  .github/workflows/deploy-docs.yml
  .github/workflows/pr-docs.yml
Labels: area/dependency, area/documentation, pr/needs review, priority/low

#1896 Add stop grace period
  docker-compose.yml
Labels: area/enhancement, kind/improvement

#1895 fail2ban cleanup
  Dockerfile
  config/fail2ban-fail2ban.cf
  config/fail2ban-jail.cf
  target/fail2ban/filter.d/postfix-sasl.conf
  target/fail2ban/jail.conf
  target/fail2ban/jail.local
  target/scripts/startup/setup-stack.sh
  test/mail_fail2ban.bats
Labels: area/enhancement, kind/improvement, service/fail2ban

#1899 small docu enhancements
  docs/content/config/advanced/full-text-search.md
Labels: area/documentation, area/enhancement, kind/improvement

#1898 Enhance setup.sh email list
  target/bin/listmailuser
  test/tests.bats
Labels: area/enhancement, kind/improvement

#1908 POP3 warning removed
  docs/content/config/pop3.md
Labels: area/documentation, kind/improvement

#1910 Fix typo
  docs/content/config/pop3.md
Labels: area/documentation, kind/improvement

#1909 Comments added
  docker-compose.yml
Labels: area/enhancement, kind/improvement

#1912 Backup script improved
  docs/content/faq.md
Labels: area/documentation, kind/improvement

#1902 Add LDAP_QUERY_FILTER_SENDERS setting for spoof protection with LDAP
  Dockerfile
  ENVIRONMENT.md
  docs/content/config/advanced/auth-ldap.md
  target/postfix/ldap-senders.cf
  target/scripts/startup/setup-stack.sh
  test/mail_with_ldap.bats
  test/test-files/auth/ldap-smtp-auth-spoofed-sender-with-filter-exception.txt
Labels: area/enhancement, pr/needs review, priority/low, service/ldap

#1913 [Documentation] mail_crypt plugin
  docs/content/config/advanced/override-defaults/dovecot.md
  docs/content/config/security/mail_crypt.md
Labels: area/documentation, area/features, kind/improvement, priority/low

#1914 Fail2Ban block behaviour
  ENVIRONMENT.md
  config/fail2ban-jail.cf
  mailserver.env
  target/fail2ban/jail.local
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
  test/config/fail2ban-jail.cf
  test/mail_fail2ban.bats
Labels: area/enhancement, area/features, kind/improvement, kind/new feature, service/fail2ban

#1917 docs(deps): update mkdocs-material to v7.1.2
  .github/workflows/deploy-docs.yml
  .github/workflows/pr-docs.yml
Labels: area/ci, area/dependency, area/documentation, pr/needs review, priority/low

#1918 Adjusted documentation for service name and Traefik certificate issuance
  docs/content/config/security/ssl.md
  target/scripts/startup/setup-stack.sh
Labels: area/documentation, kind/improvement, meta/needs triage, priority/medium

#1901 Use dovecot's LDAP uris option instead of hosts (fixes #1510)
  ENVIRONMENT.md
  target/dovecot/dovecot-ldap.conf.ext
  target/scripts/startup/setup-stack.sh
  test/mail_with_ldap.bats
Labels: area/enhancement, pr/needs review, priority/medium, service/ldap

#1922 Missing example added
  config/fail2ban-jail.cf
Labels: area/enhancement, area/scripts, kind/improvement

#1924 Link updated
  docs/content/examples/tutorials/basic-installation.md
Labels: area/documentation, kind/improvement

#1931 ENABLE_QUOTAS added
  mailserver.env
Labels: area/enhancement, kind/improvement

#1934 docs(deps): bump mkdocs-material to 7.1.3
  .github/workflows/deploy-docs.yml
  .github/workflows/pr-docs.yml
Labels: area/ci, area/dependency, area/documentation, kind/improvement, pr/needs review, priority/medium
