Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-07, with the labels that each got.

#2064 add dovecot-fts-xapian
  Dockerfile
  docs/content/config/advanced/full-text-search.md
Labels: area/documentation, area/features, kind/new feature, service/dovecot

#2071 fix: wrong contribution type
  .all-contributorsrc
Labels: kind/bug, pr/needs review, priority/high

#2072 fix: add cli tool fix
  .all-contributorsrc
Labels: kind/bug, pr/needs review, priority/high

#2076 fix: add missing curly brace
  .all-contributorsrc
Labels: kind/bug, priority/high

#2081 CONTRIBUTING.md "moved" to documentation
  CONTRIBUTING.md
  README.md
Labels: area/documentation, kind/improvement

#2082 docs(deps): bump mkdocs-material to 7.1.10
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, area/dependency, area/documentation, area/security, kind/improvement, pr/needs review

#2087 docs(deps): bump mkdocs-material to 7.1.11
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/documentation, kind/improvement, pr/needs review, priority/low

#2093 docs(deps): bump mkdocs-material to 7.2.0
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/documentation, kind/improvement, pr/needs review, priority/low

#2099 docs(deps): bump mkdocs-material to 7.2.1
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/dependency, area/documentation, pr/needs review, priority/low

#2103 chore: add note regarding past contributions
  CONTRIBUTORS.md
Labels: kind/improvement, pr/needs review

#2105 Update AWS SES configuration doc
  docs/content/config/advanced/mail-forwarding/aws-ses.md
Labels: area/documentation, kind/improvement

#2107 docs: add blog posts section
  docs/content/examples/tutorials/blog-posts.md
  docs/mkdocs.yml
Labels: area/documentation, kind/improvement, pr/needs review, priority/low
