Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-03, with the labels that each got.

#1851 Fix update docs to use `setup.sh help`
  README.md
Labels: area/documentation, kind/improvement, priority/medium

#1852 Use time zone from host
  docker-compose.yml
Labels: area/enhancement, kind/improvement, priority/low

#1862 Make directory with parent directories
  target/bin/generate-ssl-certificate
Labels: area/enhancement, area/scripts, kind/improvement, priority/low

#1864 fix for #1808
  setup.sh
  target/bin/addmailuser
  target/bin/delmailuser
Labels: area/enhancement, area/issue, area/scripts, kind/improvement, priority/medium

#1866 Introduce ENABLE_AMAVIS env
  ENVIRONMENT.md
  mailserver.env
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
Labels: area/documentation, area/features, area/scripts, kind/new feature

#1869 Fix SpamAssassin spelling/typos
  Dockerfile
  ENVIRONMENT.md
  README.md
  docs/content/faq.md
  mailserver.env
  target/scripts/startup/fixes-stack.sh
  target/scripts/startup/setup-stack.sh
Labels: area/documentation, area/enhancement, kind/improvement, priority/low

#1870 chore: update changelog
  CHANGELOG.md
Labels: area/documentation, pr/needs review, priority/low

#1874 Fix for #1808
  setup.sh
Labels: kind/improvement, pr/needs review, priority/medium
