Repository docker-mailserver/docker-mailserver, pull requests merged in 2021-05, with the labels that each got.

#1945 Add supervisord stop grace period
  target/supervisor/conf.d/supervisor-app.conf
Labels: area/scripts, kind/improvement

#1947 introduce variable to control Amavis' loglevel
  ENVIRONMENT.md
  docs/content/config/advanced/override-defaults/user-patches.md
  mailserver.env
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
  test/mail_disabled_clamav_spamassassin.bats
  test/tests.bats
Labels: area/scripts, kind/improvement, priority/low

#1949 docs(deps): bump mkdocs-material to 7.1.4
  .github/workflows/deploy-docs.yml
  .github/workflows/pr-docs.yml
Labels: area/ci, area/dependency, area/documentation, pr/needs review, priority/low

#1948 Outsourcing Environment Variables to the Documentation
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  compose.env
  docker-compose.yml
  docs/content/config/advanced/auth-ldap.md
  docs/content/config/environment.md
  docs/content/config/security/ssl.md
  docs/content/config/setup.sh.md
  docs/content/config/troubleshooting/debugging.md
  docs/content/contributing/coding-style.md
  docs/content/contributing/issues-and-pull-requests.md
  docs/content/examples/tutorials/basic-installation.md
  docs/content/index.md
  docs/mkdocs.yml
  mailserver.env
Labels: area/documentation, kind/improvement, priority/medium

#1965 introduce F2B v0.11
  Dockerfile
  test/mail_fail2ban.bats
Labels: area/dependency, kind/improvement, meta/needs triage, pr/needs review, priority/medium, service/fail2ban

#1970 Add ARM platforms
  .github/workflows/test_merge_requests.yml
Labels: area/ci, kind/improvement

#1972 Use buildx in test_merge_requests.yml
  .github/workflows/test_merge_requests.yml
Labels: area/ci, area/tests, kind/improvement, pr/needs review, priority/high

#1974 CI fix for #1972
  .github/workflows/test_merge_requests.yml
Labels: area/ci, kind/improvement

#1971 ARM build fix
  Dockerfile
Labels: area/ci, area/issue, pr/needs review, priority/medium

#1975 Remove stable branch from CI and build edge on schedule
  .github/workflows/default_on_push.yml
  .github/workflows/linting.yml
  .github/workflows/scheduled_builds.yml
Labels: area/ci, kind/improvement, priority/low

#1976 Add version variable
  Dockerfile
  target/scripts/start-mailserver.sh
Labels: area/scripts, kind/improvement, priority/low

#1951 Update check
  .dockerignore
  Dockerfile
  VERSION
  docs/content/config/environment.md
  mailserver.env
  target/scripts/start-mailserver.sh
  target/scripts/startup/daemons-stack.sh
  target/scripts/update-check.sh
  target/supervisor/conf.d/supervisor-app.conf
Labels: area/features, area/scripts, kind/new feature

#1988 docs(ci): Deploy Previews
  .github/workflows/docs-preview-deploy.yml
  .github/workflows/docs-preview-prepare.yml
  .github/workflows/docs-production-deploy.yml
  .github/workflows/pr-docs.yml
  .github/workflows/scripts/docs/build-docs.sh
  .github/workflows/scripts/docs/update-versions-json.sh
  docs/content/assets/logo/.src/dmo-logo-white.png
  docs/content/assets/logo/.src/dmo-logo-white.svg
  docs/content/assets/logo/.src/dmo-logo.png
  docs/content/assets/logo/.src/dmo-logo.svg
  docs/content/assets/logo/dmo-logo-white.min.svg
  docs/content/assets/logo/dmo-logo-white.svg
  docs/content/assets/logo/dmo-logo.min.svg
  docs/content/assets/logo/dmo-logo.svg
  docs/content/assets/logo/src/dmo-logo-white.png
  docs/content/assets/logo/src/dmo-logo-white.svg
  docs/content/assets/logo/src/dmo-logo.png
  docs/content/assets/logo/src/dmo-logo.svg
  docs/mkdocs.yml
  docs/overrides/404.html
  docs/overrides/assets/img/bg-water.webp
  docs/overrides/favicon.ico
Labels: area/ci, area/documentation, kind/new feature, priority/medium

#1985 docs(deps): bump mkdocs-material to 7.1.5
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, area/dependency, area/documentation, pr/needs review

#1990 fix: add link to netlify
  .github/workflows/docs-preview-prepare.yml
Labels: area/documentation, pr/needs review, priority/high

#1992 chore: add recreate option for comment of doc preview
  .github/workflows/docs-preview-deploy.yml
Labels: area/ci, area/documentation, kind/improvement, pr/needs review

#1993 Add Kmail as sieve client
  docs/content/config/advanced/mail-sieve.md
Labels: area/documentation, kind/improvement, pr/needs review, priority/low

#1921 docs(ldap): Improve LDAP documentation
  docs/content/config/advanced/auth-ldap.md
Labels: area/documentation, kind/improvement, meta/wip, priority/medium, service/ldap

#1994 fix email list
  setup.sh
Labels: area/scripts, kind/improvement, priority/medium

#1989 fix!: Allow protocol in SASLAUTHD_LDAP_SERVER & adjust SASLAUTHD_LDAP_ default values
  docs/content/config/advanced/auth-ldap.md
  docs/content/config/environment.md
  docs/content/examples/uses-cases/forward-only-mailserver-with-ldap-authentication.md
  mailserver.env
  target/scripts/startup/setup-stack.sh
  test/mail_with_ldap.bats
Labels: area/documentation, area/issue, area/scripts, kind/improvement, pr/needs review, priority/high, service/ldap

#2002 chore: remove @radicand and add labels
  .github/dependabot.yml
Labels: area/ci, area/dependency, pr/needs review, priority/low

#2006 chore(docs): Update Kubernetes CRI-O Capability Description
  docs/content/config/advanced/kubernetes.md
Labels: area/documentation, kind/improvement, priority/low

#2015 docs(deps): bump mkdocs-material to 7.1.6
  .github/workflows/docs-preview-prepare.yml
  .github/workflows/scripts/docs/build-docs.sh
  docs/content/config/advanced/override-defaults/postfix.md
  docs/content/config/best-practices/dkim.md
  docs/content/config/best-practices/dmarc.md
  docs/content/config/best-practices/spf.md
  docs/content/examples/uses-cases/forward-only-mailserver-with-ldap-authentication.md
Labels: area/ci, area/documentation, kind/improvement, priority/low
