Repository docker-mailserver/docker-mailserver, pull requests merged in 2022-01, with the labels that each got.

#2351 Update links to dovecot docs
  config/dovecot.cf
  docs/content/config/advanced/override-defaults/dovecot.md
Labels: kind/improvement, area/documentation

#2353 tests(fix): Align with upstream `testssl` field name change
  test/security_tls_cipherlists.bats
Labels: priority/high, area/tests, kind/bugfix

#2354 Make TLS tests more reliable
  test/security_tls_cipherlists.bats
Labels: area/tests, kind/bugfix

#2342 Introduce ENABLE_DNSBL env
  docs/content/config/environment.md
  mailserver.env
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
  test/mail_dnsbl.bats
  test/mail_with_postgrey.bats
Labels: kind/new feature, service/postfix, area/features, area/documentation, area/configuration file

#2358 Introduce DOVECOT_INET_PROTOCOLS env
  docs/content/config/environment.md
  mailserver.env
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
  test/dovecot_inet_protocol.bats
Labels: kind/new feature, service/dovecot, area/scripts, area/tests, area/documentation, area/configuration file

#2357 Fix harmless startup errors
  target/bin/delmailuser
  target/bin/sedfile
  target/scripts/start-mailserver.sh
  target/scripts/startup/fixes-stack.sh
Labels: area/scripts, kind/bugfix

#2363 Add tests for sedfile wrapper
  test/sedfile.bats
Labels: area/tests, kind/improvement

#2362 add env var `LOGWATCH_SENDER`
  docs/content/config/environment.md
  mailserver.env
  target/scripts/startup/setup-stack.sh
Labels: kind/new feature, priority/low, area/scripts, area/configuration file

#2368 docs(deps): bump mkdocs-material to v8.1.6
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, priority/low, kind/improvement, area/documentation

#2374 docs(deps): bump mkdocs-material to v8.1.7
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, priority/low, kind/improvement

#2382 Fixed non-number-argument in `listmailuser`
  target/bin/listmailuser
Labels: priority/medium, area/scripts, kind/bugfix

#2384 docs: Fail2Ban - Fix links for rootless podman
  docs/content/config/security/fail2ban.md
Labels: area/documentation, kind/bugfix

#2383 SSL documentation contains a small bug #2381
  docs/content/config/security/ssl.md
Labels: priority/low, area/documentation, kind/bugfix
