Repository docker-mailserver/docker-mailserver, pull requests merged in 2022-10, with the labels that each got.

#2786 style: minor adjustments
  target/scripts/build/packages.sh
  target/scripts/helpers/log.sh
  target/scripts/helpers/utils.sh
Labels: area/scripts, kind/improvement, area/configuration (file)

#2810 tests: Wait until container is not in starting state anymore, before running health check
  test/tests.bats
Labels: area/tests, kind/bugfix

#2808 ci: fix/improve Fail2Ban tests
  test/mail_fail2ban.bats
Labels: area/tests, kind/improvement

#2820 tests(fix): Avoid introducing CRLF into `postfix-accounts.cf` during setup
  test/tests.bats
Labels: priority/high, area/scripts, area/tests, kind/bugfix

#2790 release: `v11.2.0`
  CHANGELOG.md
  VERSION
Labels: priority/high, kind/release

#2815 ci: misc test enhancements
  .github/workflows/generic_test.yml
  Makefile
  test/clamav.bats
  test/setup-cli.bats
  test/test_helper/common.bash
  test/tests.bats
Labels: area/ci, priority/high, priority/medium, kind/bugfix

#2830 Fix typo
  target/bin/open-dkim
Labels: area/scripts, kind/bugfix

#2817 Run user-patches.sh right before starting daemons
  CHANGELOG.md
  target/scripts/start-mailserver.sh
Labels: priority/medium, area/scripts, kind/bugfix

#2818 fail2ban: enable network bans
  CHANGELOG.md
  Dockerfile
  target/scripts/build/packages.sh
  test/mail_fail2ban.bats
Labels: area/ci, service/fail2ban, kind/improvement

#2831 Fix: Run Amavis cron job only when Amavis is enabled
  CHANGELOG.md
  target/scripts/startup/setup-stack.sh
Labels: area/scripts, kind/bugfix

#2833 build: cleaned up Makefile
  .gitignore
  CHANGELOG.md
  Makefile
  test/config/templates/dovecot-masters.cf
  test/config/templates/postfix-accounts.cf
Labels: area/ci, kind/improvement

#2849 setup: fix unbound variable error
  CHANGELOG.md
  target/bin/setup
Labels: area/scripts, kind/bugfix

#2851 Fix: Make fetchmail data persistant
  CHANGELOG.md
  target/scripts/startup/misc-stack.sh
Labels: area/scripts, kind/bugfix

#2853 Follow up for #2849
  CHANGELOG.md
  target/bin/setup
Labels: area/scripts, kind/bugfix

#2859 Run fetchmail not in verbose mode
  CHANGELOG.md
  target/supervisor/conf.d/supervisor-app.conf
Labels: kind/improvement, service/fetchmail

#2854 scripts: Improve error handling, when parameters are missing
  CHANGELOG.md
  target/bin/addalias
  target/bin/adddovecotmasteruser
  target/bin/addmailuser
  target/bin/addrelayhost
  target/bin/addsaslpassword
  target/bin/delalias
  target/bin/deldovecotmasteruser
  target/bin/delmailuser
  target/bin/delquota
  target/bin/excluderelaydomain
  target/bin/open-dkim
  target/bin/setquota
  target/bin/updatedovecotmasteruser
  target/bin/updatemailuser
  target/scripts/helpers/utils.sh
Labels: area/scripts, kind/bugfix

#2870 Add OS version to issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: kind/improvement

#2876 setup.sh: Remove __err function
  setup.sh
Labels: area/scripts, kind/bugfix
