Repository docker-mailserver/docker-mailserver, pull requests merged in 2022-11, with the labels that each got.

#2881 Bugfix: './setup.sh email list' does not display aliases correctly
  target/bin/listmailuser
Labels: area/scripts, kind/bugfix

#2891 improvement: issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: kind/improvement

#2890 fix: adjust DNSBL return code interpretation
  target/postfix/main.cf
  target/scripts/startup/setup-stack.sh
  test/mail_dnsbl.bats
  test/mail_with_postgrey.bats
Labels: priority/high, service/postfix, area/security, kind/bugfix

#2892 ci: update to new output format on GH actions
  .github/workflows/contributors.yml
  .github/workflows/generic_build.yml
  .github/workflows/generic_publish.yml
Labels: area/ci, kind/update
