Repository docker-mailserver/docker-mailserver, pull requests merged in 2022-02, with the labels that each got.

#2388 Fixed typo in update-and-cleanup.md.
  docs/content/config/advanced/maintenance/update-and-cleanup.md
Labels: priority/low, kind/improvement, area/documentation

#2389 `README.md` and Documentation Update
  README.md
  docs/content/config/security/ssl.md
Labels: priority/medium, kind/improvement, area/documentation, kind/bugfix

#2401 improvement: get rid of subshell + `exec` in `helper-functions.sh`
  target/scripts/check-for-changes.sh
  target/scripts/helper-functions.sh
  test/mail_changedetector.bats
Labels: priority/high, area/scripts, kind/improvement, kind/bugfix

#2393 Rootless Podman security update
  README.md
  docs/content/config/advanced/podman.md
  mailserver.env
  target/scripts/startup/setup-stack.sh
  test/permit_docker.bats
Labels: priority/low, kind/improvement, area/documentation

#2397 fix: double occurence of `/etc/postfix/regexp`
  target/scripts/helpers/aliases.sh
  target/scripts/startup/setup-stack.sh
Labels: priority/medium, area/scripts, kind/bugfix

#2361 consistently make 1 the default value for `SPAMASSASSIN_SPAM_TO_INBOX`
  docs/content/config/environment.md
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
  test/mail_spam_bounced.bats
  test/tests.bats
Labels: area/scripts, kind/improvement, area/configuration file, stale-bot/ignore

#2410 added sieve example for subaddress sorting
  docs/content/config/advanced/mail-sieve.md
Labels: kind/improvement, area/documentation

#2404 Add changedetector functionality for `${SSL_TYPE} == manual`
  docs/content/config/advanced/auth-ldap.md
  docs/content/config/environment.md
  target/scripts/check-for-changes.sh
  target/scripts/helper-functions.sh
  target/scripts/helpers/index.sh
  target/scripts/helpers/ssl.sh
  target/scripts/startup/setup-stack.sh
  test/mail_ssl_letsencrypt.bats
  test/mail_ssl_manual.bats
Labels: kind/new feature, priority/medium, area/scripts

#2422 docs(deps): bump mkdocs-material to v8.2.1
  .github/workflows/scripts/docs/build-docs.sh
  docs/content/config/security/understanding-the-ports.md
  docs/mkdocs.yml
Labels: area/ci, area/documentation, area/configuration file

#2418 Add SpamAssassin KAM
  Dockerfile
  docs/content/config/environment.md
  mailserver.env
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
Labels: kind/new feature, priority/low, area/features, service/spamassassin

#2420 refactoring: split helper functions into smaller scripts
  Dockerfile
  target/bin/acme_extract
  target/bin/addalias
  target/bin/addmailuser
  target/bin/addrelayhost
  target/bin/addsaslpassword
  target/bin/delalias
  target/bin/delmailuser
  target/bin/delquota
  target/bin/excluderelaydomain
  target/bin/fail2ban
  target/bin/listalias
  target/bin/listmailuser
  target/bin/postfix-summary
  target/bin/print-environment
  target/bin/quota-warning
  target/bin/report-pflogsumm-yesterday
  target/bin/restrict-access
  target/bin/setquota
  target/bin/updatemailuser
  target/bin/virus-wiper
  target/dovecot/90-quota.conf
  target/scripts/check-for-changes.sh
  target/scripts/helper-functions.sh
  target/scripts/helpers/dns.sh
  target/scripts/helpers/error.sh
  target/scripts/helpers/index.sh
  target/scripts/helpers/lock.sh
  target/scripts/helpers/log.sh
  target/scripts/helpers/network.sh
  target/scripts/helpers/relay.sh
  target/scripts/helpers/sasl.sh
  target/scripts/helpers/ssl.sh
  target/scripts/helpers/utils.sh
  target/scripts/start-mailserver.sh
  target/scripts/startup/setup-stack.sh
  target/scripts/wrapper/fail2ban-wrapper.sh
  target/scripts/wrapper/postfix-wrapper.sh
  target/scripts/wrapper/postsrsd-wrapper.sh
  test/helper-functions.bats
  test/test_helper/common.bash
Labels: priority/low, priority/medium, area/scripts, kind/improvement

#2429 docs(podman): Fix broken links and add version hints
  docs/content/config/advanced/podman.md
Labels: priority/low, priority/medium, kind/improvement, area/documentation

#2426 Fix some documentation links
  README.md
  docs/content/config/advanced/mail-forwarding/relay-hosts.md
  docs/content/config/advanced/mail-sieve.md
  docs/content/config/user-management/aliases.md
  docs/content/examples/tutorials/blog-posts.md
Labels: kind/improvement, area/documentation

#2439 Update 'build' doc
  docs/content/examples/tutorials/docker-build.md
Labels: kind/improvement, area/documentation
