Repository docker-mailserver/docker-mailserver, pull requests merged in 2023-11, with the labels that each got.

#3618 docs: Fix typo "adkim=4" at DMARC section
  v12.1/config/best-practices/dkim_dmarc_spf/index.html
Labels: area/documentation, kind/bug/fix

#3626 docs: improve docs about how to work with logs
  docs/content/config/debugging.md
  docs/content/config/security/rspamd.md
Labels: kind/improvement, area/documentation

#3629 Fix rspamd directory
  docs/content/config/advanced/optional-config.md
Labels: area/documentation, kind/bug/fix

#3579 docs: Add Dovecot Lua auth guide + required package
  docs/content/examples/use-cases/auth-lua.md
  docs/mkdocs.yml
  target/scripts/build/packages.sh
Labels: kind/new feature, service/dovecot, area/features, area/documentation

#3603 docs: Clarify default for ENV `FETCHMAIL_PARALLEL`
  docs/content/config/environment.md
  mailserver.env
Labels: area/documentation

#3625 fix: Drop special bits from Postfix `maildrop/` and `public/` directory permissions
  docs/content/config/advanced/kubernetes.md
  target/scripts/startup/setup.d/mail_state.sh
Labels: area/scripts, area/documentation, kind/bug/fix

#3627 Rspamd: add check for DKIM private key files' permissions
  target/bin/rspamd-dkim
  target/scripts/helpers/rspamd.sh
  target/scripts/startup/setup.d/security/rspamd.sh
Labels: area/scripts, kind/improvement, service/security/rspamd

#3638 contributors: fix spelling & remove dedicated AllContributors section
  .github/workflows/contributors.yml
  CONTRIBUTORS.md
Labels: kind/improvement, area/documentation

#3640 docs: correct path for logs in docs
  docs/content/config/debugging.md
Labels: area/documentation, kind/update

#3652 docs: Debugging - Add macOS suggestion to use `gRPC FUSE`
  docs/content/config/debugging.md
Labels: area/documentation, os/macOS

#3650 docs: Dovecot Sieve - Adjust to new path for user home folder
  docs/content/config/advanced/mail-sieve.md
Labels: service/dovecot, area/documentation, kind/update

#3654 docs: Debugging - Correctly starting DMS
  docs/content/config/debugging.md
Labels: kind/improvement, area/documentation

#3651 docs: Example - Integrating Crowdsec
  docs/content/examples/tutorials/crowdsec.md
  docs/mkdocs.yml
Labels: area/documentation

#3655 ci: Linter EC should use `/check` as the mount path
  test/linting/lint.sh
Labels: area/ci, kind/update

#3641 release: v13.0.0
  .github/pull_request_template.md
  CHANGELOG.md
  VERSION
Labels: priority/high, kind/release

#3662 bug fix: push `:edge` when `VERSION` is updated as well
  .github/workflows/default_on_push.yml
Labels: area/ci, priority/high, kind/bug/fix

#3669 hotfix: solve #3665
  CHANGELOG.md
  docs/content/config/environment.md
  mailserver.env
  target/rspamd/local.d/settings.conf
  target/scripts/startup/setup.d/security/rspamd.sh
  test/tests/parallel/set1/spam_virus/rspamd_full.bats
Labels: priority/high, area/scripts, service/security/dkim-dmarc-spf, service/security/rspamd, kind/bug/fix

#3666 fix: `update-check.sh` should query GH Releases
  .github/workflows/default_on_push.yml
  .github/workflows/generic_publish.yml
  CHANGELOG.md
  Dockerfile
  Makefile
  docs/content/examples/tutorials/docker-build.md
  target/scripts/build/packages.sh
  target/scripts/start-mailserver.sh
  target/scripts/update-check.sh
Labels: area/ci, priority/high, area/scripts, kind/improvement

#3676 fix: Logging - Welcome should use `DMS_RELEASE` ENV
  CHANGELOG.md
  VERSION
  target/scripts/start-mailserver.sh
Labels: area/scripts, kind/bug/fix
