Repository docker-mailserver/docker-mailserver, pull requests merged in 2023-06, with the labels that each got.

#3381 ci: Simplify GH bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: area/ci, kind/improvement

#3373 Dovecot: compile `fts_xapian` from source to match Dovecot ABI
  Dockerfile
  target/scripts/build/compile.sh
  target/scripts/build/packages.sh
Labels: service/dovecot, area/features, kind/bug/fix

#3385 Don't register _setup_spam_to_junk() when SMTP_ONLY=1
  target/scripts/start-mailserver.sh
Labels: area/scripts, kind/bug/fix

#3380 Fix issue with concatenating $dmarc_milter and $dkim_milter in main.cf
  target/scripts/startup/setup.d/dmarc_dkim_spf.sh
Labels: service/postfix, area/scripts, kind/bug/fix

#3404 docs: Add compatibility section to debugging page
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/content/config/debugging.md
Labels: kind/improvement, area/documentation
