Repository docker-mailserver/docker-mailserver, pull requests merged in 2024-04, with the labels that each got.

#3980 docs: Fix typo on usage page
  docs/content/usage.md
Labels: area/documentation, kind/bug/fix

#3981 docs: Updates to TLS page (Caddy, testing, etc)
  docs/content/config/security/ssl.md
Labels: kind/improvement, area/documentation

#3982 chore: Remove base-60 port quote warning from example `compose.yaml`
  compose.yaml
Labels: area/documentation, area/configuration (file)

#3973 docs: Setup guide for relaying to and from a private DMS instance
  CHANGELOG.md
  docs/content/examples/use-cases/external-relay-only-mailserver.md
  docs/mkdocs.yml
Labels: kind/new feature, service/postfix, area/documentation
