Repository docker-mailserver/docker-mailserver, pull requests merged in 2024-11, with the labels that each got.

#4247 ci: Revise `docs-preview-deploy.yml`
  .github/workflows/docs-preview-deploy.yml
Labels: area/ci

#4262 ci(docs-preview): Refactor workflows
  .github/workflows/docs-preview-deploy.yml
  .github/workflows/docs-preview-prepare.yml
  .github/workflows/scripts/docs/build-docs.sh
Labels: area/ci, priority/high, kind/improvement, area/documentation

#4259 fix: SASLAuth - Drop services for `mysql`, `shadow`, `pam` auth mechanisms
  CHANGELOG.md
  docs/content/config/environment.md
  target/scripts/startup/variables-stack.sh
  target/supervisor/conf.d/saslauth.conf
Labels: area/features, area/documentation, kind/bug/fix

#4277 chore: Update `jaq` to `2.0.0`
  CHANGELOG.md
  target/scripts/build/packages.sh
  target/scripts/startup/setup.d/security/rspamd.sh
Labels: area/scripts, kind/update
