Repository docker-mailserver/docker-mailserver, pull requests merged in 2024-02, with the labels that each got.

#3833 rspamd: add neural module config
  CHANGELOG.md
  docs/content/config/environment.md
  mailserver.env
  target/rspamd/local.d/neural.conf
  target/rspamd/local.d/neural_group.conf
  target/scripts/startup/setup.d/security/rspamd.sh
  target/scripts/startup/variables-stack.sh
Labels: kind/new feature, area/features, service/security/rspamd

#3858 docs: misc improvements (but mostly related to Rspamd)
  .github/pull_request_template.md
  CHANGELOG.md
  docs/content/config/security/rspamd.md
Labels: kind/improvement, area/documentation

#3875 docs: fix 404 in mailserver.env and default to RSA 2048 for TLS certs
  docs/content/config/security/ssl.md
  mailserver.env
Labels: area/security, area/documentation

#3876 Rspamd: improve DKIM key generation
  target/bin/rspamd-dkim
  target/scripts/helpers/rspamd.sh
Labels: area/scripts, kind/improvement, service/security/rspamd

#3879 chore: Source Postgrey `whitelist_clients` config from Github
  CHANGELOG.md
  Dockerfile
Labels: service/security/postgrey, area/scripts, kind/improvement

#3882 docs: Complete rewrite of PROXY protocol guide
  docs/content/examples/tutorials/mailserver-behind-proxy.md
Labels: service/dovecot, service/postfix, area/security, service/security/fail2ban, kind/improvement, area/documentation, area/networking

#3890 fix: Apply SELinux security context after moving to mail-state
  CHANGELOG.md
  target/scripts/startup/setup.d/mail_state.sh
Labels: area/security, area/scripts, kind/bug/fix

#3899 fix(`setup`): `open-dkim` log for conflicting implementations
  target/bin/open-dkim
Labels: area/scripts, area/features, kind/bug/fix

#3901 fix: fetchmail environment variables
  CHANGELOG.md
  target/supervisor/conf.d/supervisor-app.conf
Labels: kind/bug/fix

#3906 Fix typo and broken README link
  docs/content/config/environment.md
  docs/content/usage.md
Labels: area/documentation

#3907 feat: Configurable number of rotated log files
  CHANGELOG.md
  docs/content/config/environment.md
  mailserver.env
  target/scripts/startup/setup.d/log.sh
  target/scripts/startup/setup.d/security/rspamd.sh
  target/scripts/startup/variables-stack.sh
Labels: kind/new feature

#3908 Rename supervisor-app.conf to dms-services.conf
  CHANGELOG.md
  target/supervisor/conf.d/dms-services.conf
  test/tests/parallel/set3/container_configuration/process_check_restart.bats
Labels: area/configuration (file)
