Repository docker-mailserver/docker-mailserver, pull requests merged in 2024-09, with the labels that each got.

#4175 fix: Dovecot LDAP config should exist
  CHANGELOG.md
Labels: service/dovecot, area/scripts, service/ldap, area/configuration (file)

#4190 dependency: update `jaq` from `1.3.0` to `1.6.0`
  CHANGELOG.md
  target/scripts/build/packages.sh
Labels: area/features, kind/update

#4199 chore: Add maintenance note for LMTP
  target/scripts/startup/setup.d/postfix.sh
Labels: service/postfix, area/scripts, kind/improvement, area/documentation

#4198 ci: add dedicated feature requests to new project automatically
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: area/ci, kind/improvement

#4191 tests(rspamd): Update GTube patterns
  CHANGELOG.md
  test/config/rspamd_full/user-patches.sh
  test/tests/parallel/set1/spam_virus/rspamd_full.bats
Labels: kind/update, service/security/rspamd

#4204 Rspamd documentation: update Abusix signup link
  docs/content/config/security/rspamd.md
Labels: area/documentation, kind/update
