Repository docker-mailserver/docker-mailserver, pull requests merged in 2024-07, with the labels that each got.

#4095 fix: Update `dovecot-fts-xapian` to `1.7.13`
  CHANGELOG.md
  Dockerfile
  target/scripts/build/compile.sh
Labels: service/dovecot, area/scripts, kind/bug/fix

#4099 docs: Update `compose.yaml` for `dovecot-solr` guide
  docs/content/examples/tutorials/dovecot-solr.md
Labels: service/dovecot, area/documentation

#4106 docs: TLS typo fix
  docs/content/config/security/ssl.md
Labels: area/documentation

#4111 docs: `docker-build.md` - Update `DOVECOT_COMMUNITY_REPO` default
  docs/content/examples/tutorials/docker-build.md
Labels: area/documentation

#4118 tests: Update `curl` note for XOAUTH2 support
  test/tests/serial/mail_with_oauth2.bats
Labels: area/tests, kind/improvement, area/documentation

#4122 docs: Refactor pages for Account Management
  CHANGELOG.md
  README.md
  docs/content/config/account-management/overview.md
  docs/content/config/account-management/provisioner/file.md
  docs/content/config/account-management/provisioner/ldap.md
  docs/content/config/account-management/supplementary/master-accounts.md
  docs/content/config/account-management/supplementary/oauth2.md
  docs/content/config/advanced/auth-oauth2.md
  docs/content/config/advanced/dovecot-master-accounts.md
  docs/content/config/advanced/mail-sieve.md
  docs/content/config/advanced/optional-config.md
  docs/content/config/advanced/podman.md
  docs/content/config/best-practices/dkim_dmarc_spf.md
  docs/content/config/debugging.md
  docs/content/config/environment.md
  docs/content/config/security/fail2ban.md
  docs/content/config/security/ssl.md
  docs/content/config/security/understanding-the-ports.md
  docs/content/config/user-management.md
  docs/content/contributing/issues-and-pull-requests.md
  docs/content/examples/tutorials/mailserver-behind-proxy.md
  docs/content/examples/use-cases/auth-lua.md
  docs/content/usage.md
  docs/mkdocs.yml
  mailserver.env
Labels: kind/improvement, area/documentation

#4120 chore: Prevent Microsoft MUAs from sending reactions
  CHANGELOG.md
  target/postfix/sender_header_filter.pcre
Labels: service/postfix, kind/improvement, area/configuration (file)

#4138 docs: Add minimal `compose.yaml` examples that demonstrate specific features
  demo-setups/fetchmail-compose.yaml
  demo-setups/relay-compose.yaml
Labels: kind/improvement, area/documentation

#4141 ci: Remove CONTRIBUTORS.md
  .all-contributorsrc
  .gitattributes
  .github/workflows/contributors.yml
  CHANGELOG.md
  CONTRIBUTORS.md
Labels: area/ci, kind/improvement

#4143 docs: Add caveat for ENV `DMS_VMAIL_UID` value compatibility
  CHANGELOG.md
  docs/content/config/environment.md
Labels: area/documentation
