Repository docker-mailserver/docker-mailserver, pull requests merged in 2024-06, with the labels that each got.

#4013 release: v14.0.0
  CHANGELOG.md
  VERSION
Labels: priority/high, kind/release

#4050 docs: `mailserver.env` improve description for `SPAM_SUBJECT`
  mailserver.env
Labels: area/documentation

#4045 Fail2ban 1.1.0
  CHANGELOG.md
  Dockerfile
  target/scripts/build/packages.sh
Labels: service/security/fail2ban, kind/update

#4060 Update logwatch ignore.conf to exclude Xapian messages about pending documents
  CHANGELOG.md
  target/logwatch/ignore.conf
Labels: area/features, area/configuration (file)

#4066 docs: Document fix for PROXY protocol with `postscreen`
  docs/content/examples/tutorials/mailserver-behind-proxy.md
Labels: service/postfix, area/documentation

#4070 docs: Add tutorial for configuring Dovecot FTS with Solr
  docs/content/examples/tutorials/dovecot-solr.md
  docs/mkdocs.yml
Labels: service/dovecot, area/documentation, kind/update

#4072 feat: Add password confirmation
  CHANGELOG.md
  target/bin/adddovecotmasteruser
  target/bin/addmailuser
  target/bin/addsaslpassword
  target/bin/updatedovecotmasteruser
  target/bin/updatemailuser
  target/scripts/helpers/database/manage/postfix-accounts.sh
Labels: area/scripts, kind/improvement

#4076 docs: Add info regarding DKIM key rotation and non-expiry
  docs/content/config/best-practices/dkim_dmarc_spf.md
Labels: area/documentation, service/security/dkim-dmarc-spf

#4088 CI: Remove reviewer assignment from Dependabot config
  .github/dependabot.yml
Labels: area/ci, kind/update
