Repository docker-mailserver/docker-mailserver, pull requests merged in 2025-08, with the labels that each got.

#4531 docs: Fix path in dkim helper script (rspamd)
  CHANGELOG.md
  docs/content/config/best-practices/dkim_dmarc_spf.md
Labels: kind/improvement, area/documentation

#4183 docs: Podman - Document how to setup DMS with Quadlet
  CHANGELOG.md
  docs/content/config/advanced/podman.md
Labels: area/documentation, stale-bot/ignore, kind/upstream

#4535 chore: disable F2B `postfix-sasl` jail
  CHANGELOG.md
  config-examples/fail2ban-jail.cf
  docs/content/config/security/fail2ban.md
  target/fail2ban/jail.local
  test/tests/parallel/set1/spam_virus/fail2ban.bats
Labels: service/security/fail2ban, area/configuration (file), kind/update

#4553 ci: update & streamline GH Actions runner images
  .github/workflows/docs-production-deploy.yml
  .github/workflows/generic_build.yml
  .github/workflows/generic_publish.yml
  .github/workflows/generic_test.yml
  .github/workflows/generic_vulnerability-scan.yml
  .github/workflows/handle_stalled.yml
  .github/workflows/linting.yml
Labels: area/ci, kind/update

#4548 chore: Remove Pyzor + Razor packages
  CHANGELOG.md
  Dockerfile
  docs/content/config/environment.md
  target/scripts/build/packages.sh
Labels: area/features, kind/update, service/security/spamassassin

#4557 chore: update externally installed software
  CHANGELOG.md
  target/scripts/build/compile.sh
  target/scripts/build/packages.sh
Labels: kind/update
