Repository docker-mailserver/docker-mailserver, pull requests merged in 2025-05, with the labels that each got.

#4464 docs(xapian): Add note about config compatibility
  docs/content/config/advanced/full-text-search.md
Labels: service/dovecot, area/documentation

#4472 docs: `mailserver.env` - Remove unsupported SASL auth mechanisms
  mailserver.env
Labels: area/documentation

#4359 feat: Enable reading env vars from files
  CHANGELOG.md
  docs/content/config/environment.md
  target/scripts/startup/variables-stack.sh
  test/tests/parallel/set3/container_configuration/env_vars_from_files.bats
Labels: kind/new feature, area/security, area/scripts, area/documentation, area/configuration (file)

#4480 chore: Typo fix for debug log
  target/scripts/startup/setup-stack.sh
Labels: kind/improvement

#4483 docs: PROXY protocol advice for Traefik should reference correct entrypoints
  docs/content/examples/tutorials/mailserver-behind-proxy.md
Labels: area/documentation, area/configuration (file), kind/bug/fix, area/networking

#4487 fix: Ensure DMS config volume can be accessed by non-root users
  CHANGELOG.md
  target/scripts/startup/setup-stack.sh
Labels: area/scripts, service/security/rspamd, kind/bug/fix

#4493 fix: `packages.sh` - Remove Postfix hostname workaround
  CHANGELOG.md
  target/scripts/build/packages.sh
Labels: service/postfix, area/scripts, kind/improvement, kind/bug/fix
