Repository docker-mailserver/docker-mailserver, pull requests merged in 2025-01, with the labels that each got.

#4305 docs: TLS (Caddy) - Revise advice on `tls internal`
  docs/content/config/security/ssl.md
Labels: area/documentation

#4322 revert "fix: fix incorrect link in README.md (#4184)"
  README.md
Labels: area/documentation, kind/update

#4321 chore: remove `VERSION` file
  .dockerignore
  .github/workflows/generic_build.yml
  CHANGELOG.md
  VERSION
Labels: priority/medium, area/configuration (file), kind/update
